### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by happysmile12321** [RyouMon/i-need-an-image#5]
need_an_image/engines/bing.py 
23: 缓存策略有问题。这个情况会导致我调用两次，第一次输入主题 : t1,第二次输入主题 ：t2。第2次会从第1次的缓存中去取而不是从爬取的结果中取。应该是缓存的问题。

**Comment by RyouMon** [comment]
你提醒了我，我在其他项目中使用这个库遇到了一些问题，当时没想到是这里的BUG

**Comment by RyouMon** [comment]
版本0.3.3解决了这个问题，现在PyPI已经是最新的了
